language: node_js
node_js:
- node
install:
- npm install gulp
- npm install
script:
- npm run build
before_deploy:
- npm version patch
deploy:
  provider: npm
  email: bhofmann@agile-is.de
  api_key:
    secure: qHtDyk/TfNrzq6b+Zny4AuCSPtT0bdIAFJ1adpH9WBPqQqxazBU9JVT2tp+c5jq3Mfval2JTCu80ObtWeyQa8bDcLJkS5LQQP2STjTdADYg6fBvX1Re+7ZQs4LXe2n6k4AuxdQ6zgsbiNP2GkxtmH4Go7/PtWk9AOiviOTmXup0gJApbpvUUSEcpL3gKWEZWtYfIRqu1IWNWlGmzaj11mnBQuYpmwHubyHinJOKzmCCY4uzoph8S4t0n2ceQSamKqKc4qqdUiPQSx8ap4nGHNFqtBSsXEmAveVP9SykCSk/GSNotzI+PF9AGNN07ZaoXVI9B+E807s8cwy/jVxgW41b6ikoY6uIxOZ1/3BcGkBpD8hKFGZz9te2Xc3qBoOg8P+qU7MyV7tMaoVC0pRVdB4rDBsKvvN8E3DcRXYYOu1hhAaoY2x7U9MMaZKHZKg9ALmWGfLv3Ybqiq70NgKMcbuL7seH0zvJqXEeIfzYy30yCB1//8TFRm/sxs0i7RbqEpV+HNxgcmn6YkzR98rqUclZxLEiDb5EGfC/ky0pnSSDeH+igMFBQaIYPU+pbJbC0B1q4XgSweNaSWcqZuWxq9teqP9ZbF2kjVma5jPjHgcHbHlvsGrXGZvOeM9TLf9QjLAavqSzcIK26pMv9NA39ssjwhZ8WyCqM6wdlYhKc9V0=
  on:
    repo: AgileIS/ais-sp-js-deployment
    branch: master
